### ISSUE TITLE
ImportError: cannot import name 'IdGenerator' from 'mmdet.core' (/home/dell/ankyo/SpatialFlow-master/mmdete

### ISSUE THREAD

**Issue by AnkyoChu** [chensnathan/SpatialFlow#1]
I was reported this question when I processing Cityscapes dataset after the modification for MMCV.
can you help me?
thx.

**Comment by chensnathan** [comment]
Hi, sorry for the late reply.

Did you install `mmdet` following the guide?

To check, you can call `python` in your terminal, then type `from mmdet.core import IdGenerator` to see if it gives you the same error.
