### ISSUE TITLE
Something wrong after modified the mmcv

### ISSUE THREAD

**Issue by manjusaka999** [chensnathan/SpatialFlow#10]
Dear author:
The last issue was closed before I could thank you for your quick answer. The final solution to the last issue was strange:After restarting the computer, the problem disappeared. o(ﾟДﾟ)っ！
But I had a new problem. o(╥﹏╥)o
When I successfully installed mmdet，I run Image_demo.py with
`config = ***/configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco.py'`
`checkpoint = '***/checkpoints/mask_rcnn_r50_caffe_fpn_mstrain-poly_3x_coco_bbox_mAP-0.408__segm_mAP-0.37_20200504_163245-42aa3d00.pth'`

The program executes correctly and displays the correct results. However, when I modified the MMCV to follow the README.md, there is something wrong：
In mmcv-full（1.0.5）:
`***/mmcv/fileio/handlers/json_handler.py`，the contents of the file look like this:

class JsonHandler(BaseFileHandler):

    def load_from_fileobj(self, file):
        return json.load(file)

    def dump_to_fileobj(self, obj, file, **kwargs):
        json.dump(obj, file, **kwargs)

    def dump_to_str(self, obj, **kwargs):
        return json.dumps(obj, **kwargs)

There is no line in the code that needs to be commented out, so I skipped this step.I took the other two steps seriously.
When I finish modifying and run Image_demo.py again, it goes wrong:
`AttributeError: 'NoneType' object has no attribute 'shape'`,
It looks like the image has not been entered correctly, but that's not the case.

Then,I run the test,py, it has the same error:
`Connected to pydev debugger (build 183.4886.43)`
`loading annotations into memory...`
`Done (t=0.24s)`
`creating index...`
`index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):`
 ` File "***/pycharm-2018.3.2/helpers/pydev/pydevd.py", line 1741, in <module>`
 `        main()`
 ` File "***/pycharm-2018.3.2/helpers/pydev/pydevd.py", line 1735, in main`
   ` globals = debugger.run(setup['file'], None, None, is_module)`
`  File "***/pycharm-2018.3.2/helpers/pydev/pydevd.py", line 1135, in run`
   ` pydev_imports.execfile(file, globals, locals)  # execute the script`
`  File "***/pycharm-2018.3.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile`
 `   exec(compile(contents+"\n", file, 'exec'), glob, loc)`
`  File "***/SpatialFlow/tools/test.py", line 191, in <module>`
  `  main()`
`  File "***/SpatialFlow/tools/test.py", line 164, in main`
    `args.show_score_thr)`
 ` File "***/SpatialFlow/mmdet/apis/test.py", line 28, in single_gpu_test`
    `result = model(return_loss=False, rescale=True, **data)`
`  File "***/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
`    result = self.forward(*input, **kwargs)`
 ` File "***/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward`
  `  return self.module(*inputs[0], **kwargs[0])`
`  File "***/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
   ` result = self.forward(*input, **kwargs)`
  `File "***/SpatialFlow/mmdet/core/fp16/decorators.py", line 51, in new_func`
   ` return old_func(*args, **kwargs)`
  `File "***/SpatialFlow/mmdet/models/detectors/base.py", line 170, in forward`
   ` return self.forward_test(img, img_metas, **kwargs)`
 ` File "***/SpatialFlow/mmdet/models/detectors/base.py", line 150, in forward_test`
 `   return self.simple_test(imgs[0], img_metas[0], **kwargs)`
 ` File "***/SpatialFlow/mmdet/models/detectors/spatialflow.py", line 158, in simple_test
    x = self.extract_feat(img)`
 ` File "***/SpatialFlow/mmdet/models/detectors/spatialflow.py", line 71, in extract_feat`
  `  x = self.neck(x)`
 ` File "***/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__`
  `  result = self.forward(*input, **kwargs)`
 ` File "***/SpatialFlow/mmdet/core/fp16/decorators.py", line 51, in new_func`
    `return old_func(*args, **kwargs)`
  `File "***/SpatialFlow/mmdet/models/necks/fpn.py", line 184, in forward`
    `prev_shape = laterals[i - 1].shape[2:]`
`AttributeError: 'NoneType' object has no attribute 'shape'`

This error seems so strange that I don't know where to start. Could you give me some advice?Thank you!

**Comment by chensnathan** [comment]
That's wired. First, add a registry for `ModulatedDeformConv2d` does not affect the codebase. Maybe the second step causes this problem. Could you provide your modified `conv_module.py`?

**Comment by manjusaka999** [comment]
> 是有线的。首先，为`ModulatedDeformConv2d`不影响代码基。也许第二步造成了这个问题。你能提供你的改装吗？`conv_module.py`?

Thank you for your quick answer. Please see this link to check the code. [conv_module.py](https://github.com/manjusaka999/mm-explore/blob/main/conv_module.py)

**Comment by manjusaka999** [comment]
> That's wired. First, add a registry for `ModulatedDeformConv2d` does not affect the codebase. Maybe the second step causes this problem. Could you provide your modified `conv_module.py`?

Thank you for your quick answer. Please see this link to check the code. [conv_module.py](https://github.com/manjusaka999/mm-explore/blob/main/conv_module.py)

**Comment by chensnathan** [comment]
You don't have `return` in your `conv_module`. The forward function show be the following:
```
    def forward(self, x, offset=None, mask=None, activate=True, norm=True):
        for layer in self.order:
            if layer == 'conv':
                if self.with_explicit_padding:
                    x = self.padding_layer(x)
                if offset is not None:
                    if mask is not None:
                        x = self.conv(x, offset, mask)
                    else:
                        x = self.conv(x, offset)
                else:
                    x = self.conv(x)
            elif layer == 'norm' and norm and self.with_norm:
                x = self.norm(x)
            elif layer == 'act' and activate and self.with_activation:
                x = self.activate(x)
        return x
```

**Comment by chensnathan** [comment]
Thanks for reporting this problem. I will update the README to avoid misleading in the second modification.

**Comment by manjusaka999** [comment]
> Thanks for reporting this problem. I will update the README to avoid misleading in the second modification.

Thank you for your great work and for your patient answers!
