### ISSUE TITLE
Some questions about  Converters for panoptic segmentation

### ISSUE THREAD

**Issue by David9591** [chensnathan/SpatialFlow#3]
Dear Author：
   Thank you for your detailed README，but I still have some questions:
In panoptic_converters/README.md, I downloaded the relevant data set from cocodataset.org, however, I can't find  panoptic_coco_categories.json, How is it acquired or generated?Could you elaborate on that, please

**Comment by chensnathan** [comment]
Hi,
The `panoptic_coco_categories.json` file can be found [here](https://github.com/cocodataset/panopticapi/blob/master/panoptic_coco_categories.json).
