### ISSUE TITLE
KeyError: 'SpatialFlow is not in the detector registry'

### ISSUE THREAD

**Issue by dalanmaobu** [chensnathan/SpatialFlow#7]
I have 1 GPU,I run the train.py : 
python train.py   /media/david/fj/wx/SpatialFlow/SpatialFlow/configs/spatialflow/spatialflow_r50_fpn_20e_coco.py 
I met a question as follows.I don't know how to solve it ,can you help me have a look?

(open-mmlab) david@vision:/media/david/fj/wx/SpatialFlow/SpatialFlow/tools$ python train.py  /media/david/fj/wx/SpatialFlow/SpatialFlow/configs/spatialflow/spatialflow_r50_fpn_20e_coco.py 
fatal: not a git repository (or any parent up to mount point /media/david)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2020-11-16 20:41:32,972 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.4.0
MMCV: 1.1.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.5.0+
------------------------------------------------------------

2020-11-16 20:41:32,973 - mmdet - INFO - Distributed training: False
2020-11-16 20:41:33,685 - mmdet - INFO - Config:
model = dict(
    type='SpatialFlow',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5),
    bbox_head=dict(
        type='SpatialFlowHead',
        num_classes=80,
        in_channels=256,
        stacked_convs=4,
        stacked_mask_convs=1,
        stacked_stuff_convs=4,
        dcn_cls_convs_idx=None,
        dcn_reg_convs_idx=None,
        dcn_mask_convs_idx=None,
        dcn_stuff_convs_idx=None,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[0.5, 1.0, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    mask_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
        out_channels=256,
        featmap_strides=[8, 16, 32]),
    mask_head=dict(
        type='FCNMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=80,
        loss_mask=dict(
            type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
    stuff_head=dict(
        type='StuffHead',
        stuff_num_classes=54,
        in_channels=256,
        feat_channels=128,
        feat_indexes=[0, 1, 2],
        feat_strides=[8, 16, 32],
        out_stride=4,
        conv_cfg=None,
        norm_cfg=dict(type='GN', num_groups=32),
        loss_stuff=dict(
            type='CrossEntropyLoss', ignore_index=255, loss_weight=0.25)))
train_cfg = dict(
    single_stage=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    single_stage_nms=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.4),
        max_per_img=100),
    single_stage_mask=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(type='PseudoSampler', add_gt_as_proposals=True),
        mask_size=28,
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    single_stage=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.4),
        max_per_img=100),
    single_stage_mask=dict(mask_thr_binary=0.5))
confidence_thr = 0.37
overlap_thr = 0.37
stuff_area_limit = 4900
using_bbox = True
bbox_overlap_thr = 0.5
dataset_type = 'CocoDataset'
data_root = 'data/panoptic_annotations_trainval2017/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='LoadAnnotations', with_bbox=True, with_mask=True, with_seg=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='SegRescale', scale_factor=1.0),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='CocoDataset',
        ann_file=
        'data/panoptic_annotations_trainval2017/annotations/panoptic_train2017_detection_format_things_only.json',
        img_prefix='data/panoptic_annotations_trainval2017/train2017/',
        with_panoptic=True,
        things_other=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='LoadAnnotations',
                with_bbox=True,
                with_mask=True,
                with_seg=True),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='SegRescale', scale_factor=1.0),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=[
                    'img', 'gt_bboxes', 'gt_labels', 'gt_masks',
                    'gt_semantic_seg'
                ])
        ],
        seg_prefix=
        'data/panoptic_annotations_trainval2017/annotations/panoptic_train2017_semantic_segmentation_things_other_pngs/'
    ),
    val=dict(
        type='CocoDataset',
        ann_file=
        'data/panoptic_annotations_trainval2017/annotations/panoptic_val2017_detection_format_things_only.json',
        img_prefix='data/panoptic_annotations_trainval2017/val2017/',
        with_panoptic=True,
        things_other=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file=
        'data/panoptic_annotations_trainval2017/annotations/panoptic_val2017_detection_format_things_only.json',
        img_prefix='data/panoptic_annotations_trainval2017/val2017/',
        with_panoptic=True,
        things_other=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(metric=['panoptic'])
images_json_file = 'data/panoptic_annotations_trainval2017/annotations/panoptic_val2017_detection_format_things_only.json'
categories_json_file = 'data/panoptic_annotations_trainval2017/annotations/panoptic_coco_categories.json'
gt_json_file = 'data/panoptic_annotations_trainval2017/annotations/panoptic_val2017.json'
gt_folder = 'data/panoptic_annotations_trainval2017/annotations/panoptic_val2017/'
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 19])
total_epochs = 20
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
segmentations_folder = './work_dirs/spatialflow_r50_fpn_20e_coco/segmentations_folder_val_pred/'
panoptic_json_file = './work_dirs/spatialflow_r50_fpn_20e_coco/panoptic_val_pred.json'
work_dir = './work_dirs/spatialflow_r50_fpn_20e_coco'
gpu_ids = range(0, 1)

Traceback (most recent call last):
  File "train.py", line 174, in <module>
    main()
  File "train.py", line 147, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/david/mmdetection/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/david/mmdetection/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/david/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 169, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'SpatialFlow is not in the detector registry'

**Comment by chensnathan** [comment]
In the log, your `mmdet` version is `2.5.0+`, while in this repo, we adopt the version of `2.3.0` (see [README](https://github.com/chensnathan/SpatialFlow#installation)). You should install `mmdet` from this repo to support `SpatialFlow`.

**Comment by dalanmaobu** [comment]
I have installed the corresponding version according to README, but this problem still exists. Could you give me an answer or some advice?

**Comment by chensnathan** [comment]
Could you provide more details about how did you install `mmdet`?

**Comment by dalanmaobu** [comment]
Hello, the problem of last time has been solved. I would like to ask: when I run test.py, the result is instance segmentation instead of&nbsp;panoptic segmentation. Is this my data problem or does the code need to be adjusted?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chensnathan/SpatialFlow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 下午5:56
收件人:&nbsp;"chensnathan/SpatialFlow"<SpatialFlow@noreply.github.com&gt;;
抄送:&nbsp;"坏小孩"<1301629037@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chensnathan/SpatialFlow] KeyError: 'SpatialFlow is not in the detector registry' (#7)





 
Could you provide more details about how did you install mmdet?

**Comment by chensnathan** [comment]
The generated panoptic map can be found in the `segmentations_folder` as provided in the [config](https://github.com/chensnathan/SpatialFlow/blob/master/configs/spatialflow/spatialflow_r50_fpn_20e_coco.py#L9).

**Comment by dalanmaobu** [comment]
I&nbsp;run&nbsp;the test.py,set the default&nbsp;--show-dir ,as follows:



but,in the&nbsp;test_result file,the results are instance segmentation as follows&nbsp;, they're not the same as in the segmentations_folder_test_pred&nbsp;.


My foundation is not good,thank you for your patient answer every time.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chensnathan/SpatialFlow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午5:23
收件人:&nbsp;"chensnathan/SpatialFlow"<SpatialFlow@noreply.github.com&gt;;
抄送:&nbsp;"坏小孩"<1301629037@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [chensnathan/SpatialFlow] KeyError: 'SpatialFlow is not in the detector registry' (#7)





 
The generated panoptic map can be found in the segmentations_folder as provided in the config.

**Comment by chensnathan** [comment]
The `show` function is developed by the `open-mmlab` team for supporting box visualization or instance segmentation visualization. We do not support to show the panoptic segmentation results when inferencing in this codebase. We save all the panoptic segmentation maps in `segmentations_folder`. Please go to the `segmentations_folder` to check the visualizations offline.
