### ISSUE TITLE
Question about the mmcv version

### ISSUE THREAD

**Issue by David9591** [chensnathan/SpatialFlow#8]
Dear Author：
I have a problem，when I run this command:
`pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html`
mmcv-full's version will be 1.2.0.
then,the program will report an error:
` f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.2.0 is used but incompatible. Please install mmcv>=1.0.5, <=1.0.5.`
I have no idea about it. Can you give me an answer or some advice？

Best wishes

**Comment by chensnathan** [comment]
You can use `pip install mmcv-full==1.0.5+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html` to install the right version for `mmcv`.
