### ISSUE TITLE
A question about tools/test.py

### ISSUE THREAD

**Issue by manjusaka999** [chensnathan/SpatialFlow#9]
Dear author：
I set up the relevant environment following the steps in the README.md . Pretraining files are also in place，when I run the test.py,  I meet a problem:
`File "****/SpatialFlow/SpatialFlow/tools/test.py", line 138, in main
    dataset = build_dataset(cfg.data.test)`
` File "****/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)`
 `File "****/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)`
`TypeError: __init__() got an unexpected keyword argument 'with_panoptic'`

I have no  idea about the keyword  'with_panoptic', Do you know how to solve this problem? Thank you very much!

**Comment by chensnathan** [comment]
The keyword `with_panoptic` is for the modified `CocoDataset`, you can find the code [here](https://github.com/chensnathan/SpatialFlow/blob/master/mmdet/datasets/coco.py#L73). You can check it in your codebase.
